namespace: wordpress

wordpress:
  image: "kofeinua/rsschool-wordpress:latest"
  replicaCount: 1
  service:
    type: NodePort
    port: 8070
    nodePort: 30080
  persistentVolume:
    size: 1Gi

mariadb:
  enabled: true
  image: "bitnami/mariadb:11.5"
  rootPasswordSecretKey: root-password
  userPasswordSecretKey: user-password
  database: "wordpress_db"
  user: "wordpress_user"
  persistentVolume:
    size: 1Gi
