apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  root-password: {{ randAlphaNum 16 | b64enc | quote }}
  user-password: {{ randAlphaNum 16 | b64enc | quote }}
