apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: 8080
          env:
            - name: WORDPRESS_DB_HOST
              value: "mariadb:3306"
            - name: WORDPRESS_DATABASE_NAME
              value: {{ .Values.mariadb.database }}
            - name: WORDPRESS_DATABASE_USER
              value: {{ .Values.mariadb.user }}
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: {{ .Values.mariadb.userPasswordSecretKey }}

          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /bitnami/wordpress
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
